//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Capture {
            get {
                object obj = ResourceManager.GetObject("Capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iti_logo {
            get {
                object obj = ResourceManager.GetObject("iti-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iti_logo_ccexpress {
            get {
                object obj = ResourceManager.GetObject("iti-logo_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iti_logo_ccexpress1 {
            get {
                object obj = ResourceManager.GetObject("iti-logo_ccexpress1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jjj_ccexpress__1_ {
            get {
                object obj = ResourceManager.GetObject("jjj_ccexpress (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_business_human_resources_strategic_planning_organi_exam_5abfc114eecf01_9872016915225162449782_ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-business-human-resources-strategic-planning-organi-exam-5abfc114eecf01.98" +
                        "72016915225162449782_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_directory_computer_software_documen_5affa827da0cd6_0618589115267041678931_ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-directory-computer-software-documen-5affa827da0cd6.0618589" +
                        "115267041678931_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_directory_computer_software_documen_5affa827da0cd61 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-directory-computer-software-documen-5affa827da0cd61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_file_manager_clip_art_computer_file_files_svg_png_icon_free_download_509195_onlin_5b62ec8ed5c4e0_6046779515332097428756 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-file-manager-clip-art-computer-file-files-svg-png-icon-fre" +
                        "e-download-509195-onlin-5b62ec8ed5c4e0.6046779515332097428756", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_file_manager_clip_art_computer_file_files_svg_png_icon_free_download_509195_onlin_5b62ec8ed5c4e0_6046779515332097428756_ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-file-manager-clip-art-computer-file-files-svg-png-icon-fre" +
                        "e-download-509195-onlin-5b62ec8ed5c4e0.6046779515332097428756_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_file_manager_clip_art_computer_file_files_svg_png_icon_free_download_509195_onlin_5b62ec8ed5c4e01 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-file-manager-clip-art-computer-file-files-svg-png-icon-fre" +
                        "e-download-509195-onlin-5b62ec8ed5c4e01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_iconfinder_symbol_account_profile_icon_5ab1460b053e92_2060138315215672430215__1__ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-iconfinder-symbol-account-profile-icon-5ab1460b053e92" +
                        ".2060138315215672430215 (1)_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_iconfinder_symbol_account_profile_icon_5ab1460b053e92_2060138315215672430215__1__ccexpress__1_ {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-iconfinder-symbol-account-profile-icon-5ab1460b053e92" +
                        ".2060138315215672430215 (1)_ccexpress (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_iconfinder_symbol_account_profile_icon_5ab1460b053e92_2060138315215672430215__2_ {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-iconfinder-symbol-account-profile-icon-5ab1460b053e92" +
                        ".2060138315215672430215 (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_iconfinder_symbol_account_profile_icon_5ab1460b053e921 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-iconfinder-symbol-account-profile-icon-5ab1460b053e92" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_user_ios_7_profile_5ab91694cef9e0_2240064815220793808478_ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-user-ios-7-profile-5ab91694cef9e0.2240064815220793808478_c" +
                        "cexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_exit_sign_emergency_exit_free_content_clip_art_door_exit_log_out_logout_sign_out_icon_5ab18ae40d0950_2011518615215848680534_ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-exit-sign-emergency-exit-free-content-clip-art-door-exit-log-out-logout-s" +
                        "ign-out-icon-5ab18ae40d0950.2011518615215848680534_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_question_mark_clip_art_ask_questions_5b229af56c2e28_9890787015289945494431_ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-question-mark-clip-art-ask-questions-5b229af56c2e28.989078701528994549443" +
                        "1_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_symbol_font_home_5ab0cf80707bf9_3959915515215368964607_ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-symbol-font-home-5ab0cf80707bf9.3959915515215368964607_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_teacher_education_final_examination_library_book_convulsions_5b37885e3d81e5_6029041715303660462519_ccexpress {
            get {
                object obj = ResourceManager.GetObject("kisspng-teacher-education-final-examination-library-book-convulsions-5b37885e3d81" +
                        "e5.6029041715303660462519_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_teacher_education_final_examination_library_book_convulsions_5b37885e3d81e51 {
            get {
                object obj = ResourceManager.GetObject("kisspng-teacher-education-final-examination-library-book-convulsions-5b37885e3d81" +
                        "e51", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_exam_ccexpress {
            get {
                object obj = ResourceManager.GetObject("online-exam_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinClipart_com_student_taking_a_test_3886471_ccexpress {
            get {
                object obj = ResourceManager.GetObject("PinClipart.com_student-taking-a-test_3886471_ccexpress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PinClipart1 {
            get {
                object obj = ResourceManager.GetObject("PinClipart1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngfind_com_lines_png_588869 {
            get {
                object obj = ResourceManager.GetObject("pngfind.com-lines-png-588869", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_red {
            get {
                object obj = ResourceManager.GetObject("user red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_red__1_ {
            get {
                object obj = ResourceManager.GetObject("user red (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
